/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package controller.admin;

import java.io.UnsupportedEncodingException;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;

import model.Class;
import model.ClassDAO;

import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

/**
 * MyEclipse Struts Creation date: 10-24-2013
 * 
 * XDoclet definition:
 * 
 * @struts.action validate="true"
 */
public class AddClass extends Action {
    /*
     * Generated Methods
     */

    /**
     * Method execute
     * 
     * @param mapping
     * @param form
     * @param request
     * @param response
     * @return ActionForward
     */
    public ActionForward execute(ActionMapping mapping, ActionForm form,
            HttpServletRequest request, HttpServletResponse response) {
        // TODO Auto-generated method stub
        try {
            request.setCharacterEncoding("gb2312");
        } catch (UnsupportedEncodingException e) {
            // TODO Auto-generated catch block
            e.printStackTrace();
        }

        try {
            String name = request.getParameter("class").trim();
            if (name.equals("")) {
            	request.setAttribute("prompt", "大项名不能为空！");
                return mapping.findForward("error");
            }
            Class cls = new Class(name);
            ClassDAO class_dao = new ClassDAO();
            class_dao.addClass(cls);

            HttpSession session = request.getSession();

            ClassDAO tmpdao = new ClassDAO();   
            session.setAttribute("class_list", tmpdao.getClasses());
            request.setAttribute("prompt", "大项添加成功！");
            return mapping.findForward("success");

        } catch (RuntimeException re) {
            re.printStackTrace(System.err);
            request.setAttribute("prompt", "大项添加失败！");
            return mapping.findForward("error");
        }
    }
}
