/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package controller.admin;

import java.io.UnsupportedEncodingException;


import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;

import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;


import model.Item;
import model.ItemDAO;


/**
 * MyEclipse Struts Creation date: 10-26-2013
 * 
 * XDoclet definition:
 * 
 * @struts.action validate="true"
 */
public class AddItem extends Action {
	/*
	 * Generated Methods
	 */

	/**
	 * Method execute
	 * 
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		// TODO Auto-generated method stub
		try {
			request.setCharacterEncoding("gb2312");
		} catch (UnsupportedEncodingException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}

		try {
			int class_sn = Integer.parseInt(request.getParameter("class_sn").trim());
			String name = request.getParameter("item").trim();
			if(class_sn==0){
				return mapping.findForward("error");
			}
			
			
			Item item = new Item(class_sn,name);
			ItemDAO item_dao = new ItemDAO();
			item_dao.addItem(item);										
			
			
			HttpSession session = request.getSession();
			
			ItemDAO tmpdao = new ItemDAO();
			session.setAttribute("item_list", tmpdao.getItem());
			
											
			return mapping.findForward("success");

		} catch (RuntimeException re) {
			re.printStackTrace(System.err);
			return mapping.findForward("error");
		}
	}
}