/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package controller.admin;

import java.io.UnsupportedEncodingException;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;

import model.Supplier;
import model.SupplierDAO;

import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

/** 
 * MyEclipse Struts
 * Creation date: 02-28-2014
 * 
 * XDoclet definition:
 * @struts.action validate="true"
 */
public class AddSupplier extends Action {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		// TODO Auto-generated method stub
		try {
            request.setCharacterEncoding("gb2312");
        } catch (UnsupportedEncodingException e) {
            // TODO Auto-generated catch block
            e.printStackTrace();
        }

        try {
            String name = request.getParameter("supplier").trim();
            if (name.equals("")) {
            	request.setAttribute("prompt", "厂家名不能为空！");
                return mapping.findForward("error");
            }
            Supplier sup = new Supplier(name);
            SupplierDAO sup_dao = new SupplierDAO();
            sup_dao.addSupplier(sup);

            HttpSession session = request.getSession();

            sup_dao = new SupplierDAO();   
            session.setAttribute("supplier_list", sup_dao.getSupplier());
            request.setAttribute("prompt", "厂家添加成功！");
            return mapping.findForward("success");

        } catch (RuntimeException re) {
            re.printStackTrace(System.err);
            request.setAttribute("prompt", "厂家添加失败！");
            return mapping.findForward("error");
        }
	}
}