/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package controller.admin;

import java.util.ArrayList;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;

import model.Class;
import model.ClassDAO;

import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

/** 
 * MyEclipse Struts
 * Creation date: 02-28-2014
 * 
 * XDoclet definition:
 * @struts.action validate="true"
 */
public class DeleteClass extends Action {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		// TODO Auto-generated method stub
		try{
			int sn = Integer.parseInt(request.getParameter("sn").trim());
						
			ClassDAO classDao = new ClassDAO();
			classDao.deleteClass(sn);
	    	ArrayList<Class> class_list;
			classDao = new ClassDAO();
			class_list = classDao.getClasses();
			HttpSession session = request.getSession();
			session.setAttribute("class_list", class_list);
			
			return mapping.findForward("success");
			
		}catch(RuntimeException re){
			re.printStackTrace(System.err);
			return mapping.findForward("error");
			}
		}
	}
