/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package controller.admin;

import java.util.ArrayList;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;

import model.Device;
import model.Item;
import model.Keeper;
import model.Model;
import model.Record;

import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

/** 
 * MyEclipse Struts
 * Creation date: 03-20-2014
 * 
 * XDoclet definition:
 * @struts.action validate="true"
 */
public class ExportHistoryRecord extends Action {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		// TODO Auto-generated method stub
		HttpSession session = request.getSession();
		model.ExportRecord.print((ArrayList<Keeper>)(session.getAttribute("keeper_list")),(ArrayList<Device>)(session.getAttribute("device_list")), (ArrayList<Item>)(session.getAttribute("item_list")),(ArrayList<Model>)(session.getAttribute("model_list")),(ArrayList<Record>)(request.getAttribute("rec_list")), request, response);

		return null;
	}
}