/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package controller.admin;

import java.io.UnsupportedEncodingException;
import java.sql.Date;
import java.util.ArrayList;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;

import model.Device;
import model.DeviceDAO;

import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

/** 
 * MyEclipse Struts
 * Creation date: 03-23-2014
 * 
 * XDoclet definition:
 * @struts.action validate="true"
 */
public class ModifyDevice extends Action {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		// TODO Auto-generated method stub
		try {
			request.setCharacterEncoding("gb2312");
		} catch (UnsupportedEncodingException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
		try{
			String sn = request.getParameter("sn").trim();
			
			int location_sn = Integer.parseInt(request.getParameter("location_sn"));
			String keeper_sn = request.getParameter("keeper_sn").trim();
			new DeviceDAO().updateDevice(sn, location_sn, keeper_sn);			
			
			HttpSession session = request.getSession();
			ArrayList<Device> dev_list = (ArrayList<Device>)(session.getAttribute("dev_list"));
			for(int k=0; k<dev_list.size(); k++){
				if(dev_list.get(k).getSn().equals(sn)){
					dev_list.get(k).setPosition(location_sn);
					dev_list.get(k).setKeeper(keeper_sn);
				}
			}
			
			return null;
			
		}catch(RuntimeException re){
			re.printStackTrace(System.err);
			return null;
		}
	}
}