/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package controller.admin;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;

import model.DeviceDAO;
import model.Keeper;

import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

/** 
 * MyEclipse Struts
 * Creation date: 03-20-2014
 * 
 * XDoclet definition:
 * @struts.action validate="true"
 */
public class SpecialQuery extends Action {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		// TODO Auto-generated method stub
		try {
            String status = request.getParameter("status");
            String isElectric = request.getParameter("isElectric");
            int loc_sn = Integer.parseInt(request.getParameter("loc_sn"));
 
            HttpSession session = request.getSession();
            Keeper admin = (Keeper)(session.getAttribute("admin"));
            if(admin.getAuthority().equals("S") || admin.getAuthority().equals("B")){
            	session.setAttribute("dev_list", new DeviceDAO().getDevice(status, isElectric, loc_sn));
                
            }else if(admin.getAuthority().equals("M")){
            	session.setAttribute("dev_list", new DeviceDAO().getDevice(status, isElectric, loc_sn, admin.getDep_sn()));
            }
            
            
            return mapping.findForward("success");
            

        } catch (RuntimeException re) {
            re.printStackTrace(System.err);
            return mapping.findForward("error");
        }
	}
}