/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package controller.front;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;

import model.Keeper;
import model.LocationDAO;

import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

/** 
 * MyEclipse Struts
 * Creation date: 03-10-2014
 * 
 * XDoclet definition:
 * @struts.action validate="true"
 */
public class DeleteLocation extends Action {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		// TODO Auto-generated method stub
		try{
			int sn = Integer.parseInt(request.getParameter("sn").trim());				
			new LocationDAO().deleteLocation(sn);
			
			HttpSession session = request.getSession();
			String keeper = ((Keeper)(session.getAttribute("keeper"))).getSn();
			session.setAttribute("loc_list", new LocationDAO().getLocation(keeper));
			
			return mapping.findForward("success");
			
		}catch(RuntimeException re){
			re.printStackTrace(System.err);
			return mapping.findForward("error");
			}
		}
}
