/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package controller.front;

import java.io.UnsupportedEncodingException;
import java.sql.Date;
import java.text.SimpleDateFormat;
import java.util.ArrayList;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;

import model.Device;
import model.DeviceDAO;
import model.Record;
import model.RecordDAO;

import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

/** 
 * MyEclipse Struts
 * Creation date: 03-14-2014
 * 
 * XDoclet definition:
 * @struts.action validate="true"
 */
public class FaultRegister extends Action {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		// TODO Auto-generated method stub
		try {
            request.setCharacterEncoding("gb2312");
        } catch (UnsupportedEncodingException e) {
            // TODO Auto-generated catch block
            e.printStackTrace();
        }

        try {
            String device_sn = request.getParameter("dev_sn");
            String fault = request.getParameter("fault");
            
            java.util.Date dt = new java.util.Date();      
            SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");   
            Date fault_date = Date.valueOf(sdf.format(dt));
            
            new RecordDAO().addRecord(new Record(device_sn, fault, fault_date));
            new DeviceDAO().updateDevice(device_sn, "F");
            
            HttpSession session = request.getSession();
            ArrayList<Device> dev_list = (ArrayList<Device>)(session.getAttribute("dev_list"));
            for(int k = 0; k< dev_list.size(); k++){
            	if(dev_list.get(k).getSn().equals(device_sn)){
            		dev_list.get(k).setStatus("F");
            	}
            }

            return null;

        } catch (RuntimeException re) {
            re.printStackTrace(System.err);
            return null;
        }
	}
}