/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package controller.front;


import java.util.ArrayList;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;

import model.Device;
import model.DeviceDAO;
import model.RecordDAO;

import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

/** 
 * MyEclipse Struts
 * Creation date: 03-16-2014
 * 
 * XDoclet definition:
 * @struts.action validate="true"
 */
public class Finish extends Action {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		// TODO Auto-generated method stub
        try {
            int sn = Integer.parseInt(request.getParameter("sn"));
            String device_sn = request.getParameter("device_sn");
            if(new RecordDAO().getSingleRecord(sn).getRepair() == null){
            	request.setAttribute("emg", "未完成，维修记录不能为空！");
            	return mapping.findForward("success");
            }
            new RecordDAO().finish(sn);
            new DeviceDAO().updateDevice(device_sn, "G");
            
            HttpSession session = request.getSession();
            ArrayList<Device> dev_list = (ArrayList<Device>)(session.getAttribute("dev_list")); 
           
            for(int k=0; k<dev_list.size(); k++){
            	if(dev_list.get(k).getSn().equals(device_sn)){
            		dev_list.get(k).setStatus("G");
            	}
            }
          
            return mapping.findForward("success");

        } catch (RuntimeException re) {
            re.printStackTrace(System.err);
            return null;
        }
	}
}