/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package controller.front;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;

import model.ClassDAO;
import model.DepartmentDAO;
import model.DeviceDAO;
import model.ItemDAO;
import model.KeeperDAO;
import model.LocationDAO;
import model.ModelDAO;
import model.SupplierDAO;

import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

/** 
 * MyEclipse Struts
 * Creation date: 03-22-2014
 * 
 * XDoclet definition:
 * @struts.action validate="true"
 */
public class Index extends Action {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		// TODO Auto-generated method stub
		try {
			HttpSession session = request.getSession();
			
			session.setAttribute("class_list", new ClassDAO().getClasses());
			session.setAttribute("item_list", new ItemDAO().getItem());
			session.setAttribute("supplier_list", new SupplierDAO().getSupplier());
			session.setAttribute("model_list", new ModelDAO().getModel());
			session.setAttribute("dev_list", new DeviceDAO().getDevice(0,0,0,"",""));
			session.setAttribute("device_list", new DeviceDAO().getDevice(0,0,0,"",""));
			session.setAttribute("loc_list", new LocationDAO().getAllLocation());
			session.setAttribute("keeper_list", new KeeperDAO().query_keeper());
			session.setAttribute("dep_list", new DepartmentDAO().getDepartments());
			
			return mapping.findForward("success");
            

        } catch (RuntimeException re) {
            re.printStackTrace(System.err);
            return null;
        }
	}
}